
# TODO Do not edit this file directly! Instead, create a new file called
#        hw03_username.py and copy this code into it!

#################################################################################
# Author: Nicholas Hamilton
# Username:
#
# Assignment:
# Purpose:
# Google Doc Link:
#
#################################################################################
# Acknowledgements:
#
#
#################################################################################


import turtle

# to demonstrate the git process
def function_1():
    """
    Example docstring for function_1. function_1 is not a good function name and should be changed.
    """
    pass
    # ....


def function_2():
    """
    Example docstring for function_2. function_2 is not a good function name and should be changed.
    """
    pass
    # ...


def main():
    """
    Docstring for main. Should describe the main functionality of this file.
    """

    # Function calls to function_1 and function_2.
    function_1()            # TODO  Remove when you replace it with your function
    function_2()            # TODO  Remove when you replace it with your function


main()  # Starts the program!